package View;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.io.PrintWriter;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LessonTemplate extends javax.swing.JFrame {

    // questions and answers don't change, they can be final
    final String classStructureStart = "public class q1 {\npublic static void main(String[] args){\n";
    final String classStructureEnd = "\n}\n}";
    final String rightAnswer = "You are correct!";
    final String wrongAnswer = "You are incorrect.";
    final String question1 = "Print out 'Hello World'";
    final String question2 = "Create a enchanced for loop w/ output 123.";
    final String question3 = "Write a program that displays Jared.";
    final String answer1 = "System.out.println(\"Hello World\");";
    final String answer2 = "";
    final String answer3 = "";

    // question number and answer are static since we need them stored over multiple instances
    public static int qNum = 0;
    public static int correctAnswers = 0;
    String storeInput;

    // questions are the same every time, so it doesn't need static
    String[] questions;
    String[] answers;

    public LessonTemplate() {
        questions = new String[3];
        answers = new String[3];

        // intialize components and get questions
        initComponents();
        setResizable(false);
        questions();
        answers();

        // after generating a button, change the question number
        qNum += 1;
    }

    public String[] questions(){
        // add the questions to the string list
        questions[0] = question1;
        questions[1] = question2;
        questions[2] = question3;

        // set the label to the appriorate question
        jLabel2.setText(questions[qNum]); 

        return questions;
    }

    public String[] answers() {
        // add answeres to string list
        answers[0] = answer1;
        answers[1] = answer2;
        answers[2] = answer3;

        return answers;
    }

//    private void jLabel1ActionPerformed(java.awt.event.ActionEvent evt){
//        jLabel1.setText(questions().toString());
//        System.out.println(questions().toString());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Detente", 1, 24)); // NOI18N
        jLabel1.setText("Lesson ");

        jLabel2.setText("Question here **");

        jLabel3.setText("Your answer below");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // this creates a file called q1.java
            PrintWriter pw = new PrintWriter("q1.java");
            pw.write(classStructureStart + jTextArea1.getText() + classStructureEnd);
            pw.close();            

            // this below can get the specific directory you are in and is running command line promts with the file we made
            storeInput = runCmd("javac " +  new File("").getAbsolutePath() + "\\q1.java");
            if(!storeInput.equals("")){
                throw new Exception(storeInput);
            }

            // NO MORE HARDCODING!!!!!
            storeInput = runCmd("echo Main-Class: q1 > " + new File("").getAbsolutePath() + "\\manifest.txt");

            // this runs the file
            storeInput = runCmd("java q1");

            // then gives the result of the file from the textbox
            JOptionPane.showMessageDialog(null,storeInput);

            System.out.println(new File("").getAbsolutePath());

        // below is if the user gets it wrong it gives the error message 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LessonTemplate.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(LessonTemplate.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

        // this is the case statement that checks the answer for questions
        switch(qNum){
            case 0:
                q1(storeInput);                
                break;
            case 1:
                q2(storeInput);
                break;
            case 2:
                q3(storeInput);
                break;
        }

        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //these below are methods that are for each question
    //it has two responses if they get it right and wrong
    //prompts what the compiler resulted in
    //promts the number of correct answers
    public void q1(String storeInput){
        // lets see what the answer was supposed to be
        System.out.println("The answer was: " + questions[qNum]);

        if(storeInput.equals(answers[qNum])){
           String result =(rightAnswer);
           correctAnswers++;
           JOptionPane.showMessageDialog(null,result);
           JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
       }
       else{
           String result = (wrongAnswer);
           JOptionPane.showMessageDialog(null,result);
           JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
       }
    }

    public void q2(String storeInput){
        // lets see what the answer was supposed to be
        System.out.println("The answer was: " + questions[qNum]);

        if(storeInput.equals(answers[qNum])){
            String result =(rightAnswer);
            correctAnswers++;
            JOptionPane.showMessageDialog(null,result);
            JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
        }
        else{
            String result = (wrongAnswer);
            JOptionPane.showMessageDialog(null,result);
            JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
        }
    }

    public void q3(String storeInput){
        // lets see what the answer was supposed to be
        System.out.println("The answer was: " + questions[qNum]);

        if(storeInput.equals(answers[qNum])){
           String result =(rightAnswer);
           correctAnswers++;
           JOptionPane.showMessageDialog(null,result);
           JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
       }
       else{
           String result = (wrongAnswer);
           JOptionPane.showMessageDialog(null,result);
           JOptionPane.showMessageDialog(null,"Correct Answers: " + correctAnswers + "/3");
       }
    }

    public static String runCmd(String command) throws Exception {
        ProcessBuilder builder = new ProcessBuilder(
            "cmd.exe", "/c", command);
        builder.redirectErrorStream(true);
        Process p = builder.start();
        BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
        BufferedReader r2 = new BufferedReader(new InputStreamReader(p.getErrorStream()));
        String line;
        String br = "";
        while (true) {
            line = r.readLine();
            if (line == null) { break; }
            br+= line;
            System.out.println(line);
        }

        return br;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonTemplate().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
